apiVersion: apps/v1
kind: Deployment
metadata:
  name: depl-mongo-orious
  labels:
    app: mongo-orious
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-orious
  template:
    metadata:
      labels:
        app: mongo-orious
    spec:
      containers:
        - name: mongo-orious
          image: mongo
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: srv-mongo
spec:
  selector:
    app: mongo-orious
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

